import { test, expect } from '@playwright/test';
test('test travekfika', async ({ page }) => {
  test.setTimeout(60000);
  await page.goto('https://www.travelfika.com/');
  await page.waitForTimeout(3000);
  await page.getByRole('link', { name: 'Sign in or join using your' }).click();
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).fill('vonak40929@brixozu.com');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('vonak40929@brixozu.coM');
  await page.getByRole('checkbox', { name: 'Remember me' }).check();
  await page.getByRole('button', { name: 'Sign In' }).click();
  await page.getByRole('textbox', { name: 'Departing from?' }).click();
  await page.getByRole('textbox', { name: 'Departing from?' }).fill('ahme');
  await page.locator('div').filter({ hasText: /^AMD - Sardar Vallabhbhai Patel International AirportAhmedabad, India$/ }).first().click();
  await page.getByRole('textbox', { name: 'Going to?' }).click();
  await page.getByRole('textbox', { name: 'Going to?' }).fill('toronto');
  await page.locator('div').filter({ hasText: /^YYZ - Lester B\. Pearson International AirportToronto, Canada$/ }).first().click();
  await page.getByRole('button', {name: 'showing selected date'}).click();
  await expect(page.locator(".rdp-root.p-3")).toBeVisible();
  await page.getByRole('button', { name: 'Thursday, June 18th, 2026' }).dispatchEvent('click');
  await page.getByRole('button', { name: 'Saturday, July 4th, 2026' }).nth(1).dispatchEvent('click');
  await page.getByRole('button', { name: 'Economy' }).click();
  await page.getByRole('menuitem', { name: 'Business class' }).click();
  await page.getByRole('button', { name: 'Passenger' }).click();
  await page.getByRole('button').filter({ hasText: /^$/ }).nth(4).click();
  await page.locator('div:nth-child(3) > .flex.items-center.justify-between > .flex.items-center > button:nth-child(3)').click();
  await page.locator('div:nth-child(2) > .flex.items-center.justify-between > .flex.items-center > button:nth-child(3)').click();
  await page.getByRole('button', { name: 'Search' }).click();
});